### ISSUE TITLE
Peer review from Fatime Selimi

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/DSCI_522_Group_10#62]
Hi there 👋 

I find your project quite interesting and was able to see the relevance of a machine learning classification model on predicting customers that would subscribe to the term deposit product of a bank.
Here are a few suggestions:

- _Documentation_:
The structure of the project repository is well-organized and very easy to navigate.
The rendered format looks great. Very easy to follow.
The readme portion of the repository is well-written and very comprehensible. The same applies to the report file. 

- _Code_:
The code is well written and structured with proper documentation; functions include docstrings as well as comments where needed.
I faced some errors when I tried to run the `Makefile`. Maybe you should consider adding `jupyter_contrib_nbextensions` in your `env` file.

```
Traceback (most recent call last):
  File "/Users/fatse/opt/miniconda3/envs/bank/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/Users/fatse/.local/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/fatse/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 837, in launch_instance
    app.start()
  File "/Users/fatse/opt/miniconda3/envs/bank/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/Users/fatse/opt/miniconda3/envs/bank/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 519, in convert_notebooks
    self.exporter = cls(config=self.config)
  File "/Users/fatse/opt/miniconda3/envs/bank/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 325, in __init__
    super().__init__(config=config, **kw)
  File "/Users/fatse/opt/miniconda3/envs/bank/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
    self._init_preprocessors()
  File "/Users/fatse/opt/miniconda3/envs/bank/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 490, in _init_preprocessors
    super()._init_preprocessors()
  File "/Users/fatse/opt/miniconda3/envs/bank/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 266, in _init_preprocessors
    self.register_preprocessor(preprocessor, enabled=True)
  File "/Users/fatse/opt/miniconda3/envs/bank/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 227, in register_preprocessor
    preprocessor_cls = import_item(preprocessor)
  File "/Users/fatse/.local/lib/python3.8/site-packages/traitlets/utils/importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_contrib_nbextensions'
make: *** [src/bank_marketing_data_eda.html] Error 1
```

- _Communication_:
In general, the proposal and the final report are very clear and easy to understand - the methods used and the outcome of the prediction task is well articulated. Good job!!

- _Suggestion_:
I would suggest removing unused references from the README file and keep only the ones that you're actually referring to in the About section.

**Comment by JuntingHe** [comment]
Thank you so much for the review and feedback! We will look into it.

**Comment by anodaini** [comment]
Addressed! Thank you Fatime!
